server:
  port: 9002

spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: test
    password: test
  jpa:    hibernate:      ddl-auto: update